import { useMDXComponent } from "next-contentlayer2/hooks";
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "@/components/mdx/accordion";
import { Badge } from "@/components/mdx/badge";
import { Blockquote } from "@/components/mdx/blockquote";
import { Callout } from "@/components/mdx/callout";
import { Steps, Step } from "@/components/mdx/steps";
import {
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
} from "@/components/mdx/tabs";
import { Tree, TreeItem } from "@/components/mdx/tree";
import { FileTree } from "@/components/mdx/file-tree";
import { Headings } from "@/components/mdx/headings";
import { H1, H2, H3, H4, H5, H6 } from "@/components/mdx/heading";
import {
  Paragraph,
  Lead,
  Intro,
  Large,
  Small,
  Muted,
} from "@/components/mdx/paragraph";
import { Math, BlockMath, InlineMath, M, BM } from "@/components/mdx/math";
import {
  Mermaid,
  MermaidBST,
  MermaidTree,
  MermaidBFS,
  MermaidDFS,
} from "@/components/mdx/mermaid";
import {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableRow,
  TableHead,
  TableCell,
  TableCaption,
} from "@/components/mdx/table";
import { CodeGroup } from "@/components/mdx/code-group";
import { Alert, AlertTitle, AlertDescription } from "@/components/mdx/alert";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
  LinkCard,
} from "@/components/mdx/card";
import { Kbd } from "@/components/mdx/kbd";
import { Link } from "@/components/mdx/link";
import { Spoiler } from "@/components/mdx/spoiler";
import { Annotation } from "@/components/mdx/annotation";
import { Reveal } from "@/components/mdx/reveal";
import { Preview } from "@/components/mdx/preview";
import { Demo } from "@/components/demo";
import { SymbolBrowser } from "@/components/symbol-browser";
import { DocsCodeBlock } from "@/components/docs-code-block";
import { Sandbox } from "@/components/sandbox";
import { GlossaryProvider, Term } from "@/components/mdx/glossary";
import { Video } from "@/components/mdx/video";
import { Image, ImageGlossary } from "@/components/mdx/image";
import { DataTable } from "@/components/mdx/data-table";
import { Highlight } from "@/components/mdx/highlight";
import { DiffBlock } from "@/components/mdx/diff-block";
import { Terminal, TerminalLine } from "@/components/mdx/terminal";
import {
  Changelog,
  ChangelogEntry,
  ChangelogItem,
} from "@/components/mdx/changelog";
import { JsonLd } from "@/components/mdx/json-ld";
import { Definition } from "@/components/mdx/definition";
import { Invariant } from "@/components/mdx/invariant";
import { ComplexityTable } from "@/components/mdx/complexity-table";
import { HardwareSpec } from "@/components/mdx/hardware-spec";
import { DataTypeTable } from "@/components/mdx/data-type-table";
import { SecurityNote } from "@/components/mdx/security-note";
import { RegisterMap } from "@/components/mdx/register-map";
import { PrivacyTable } from "@/components/mdx/privacy-table";
import { CertificationBadge } from "@/components/mdx/certification-badge";
import {
  Abs,
  Aleph,
  Alpha,
  Amalg,
  And,
  Angle,
  AngleBracket,
  Angstrom,
  Approaches,
  Approx,
  Arc,
  ArcCos,
  ArcSin,
  ArcTan,
  Arg,
  Arrow,
  AsympEq,
  Aut,
  Bar,
  Because,
  Beta,
  Beth,
  BigAnd,
  BigIntersect,
  BigOr,
  BigUnion,
  Bot,
  Bowtie,
  Bra,
  Brace,
  BraKet,
  Bullet,
  Cardinality,
  Case,
  Cases,
  CC,
  CDots,
  Ceil,
  ChemEquilibrium,
  Chi,
  Choose,
  Circle,
  CircleArrow,
  CircleArrowLeft,
  CircledDiv,
  CircledMinus,
  CircledPlus,
  CircledStar,
  CircledTimes,
  Complex,
  Compose,
  CondProb,
  Cong,
  Conj,
  ContourIntegral,
  Contradiction,
  Convo,
  Corr,
  Corresponds,
  Cos,
  Cosh,
  Cot,
  Cov,
  Cross,
  Csc,
  Cubed,
  Dagger,
  Daleth,
  DDot,
  DDots,
  DefEq,
  DefinedAs,
  Deg,
  DegNum,
  DeltaU,
  Der,
  Deriv,
  Det,
  Diameter,
  Diamond,
  Differential,
  Digamma,
  Dim,
  DirectSum,
  Dist,
  Divides,
  Division,
  Dot,
  DotAccent,
  DoubleBond,
  DoubleBracket,
  DoubleDagger,
  DoubleDownArrow,
  DoubleHarpoon,
  DoubleInt,
  DoubleLeftArrow,
  DoubleLeftRightArrow,
  DoublePrime,
  DoubleRightArrow,
  DoubleUpArrow,
  DoubleUpDownArrow,
  DownArrow,
  Ellipse,
  EllTwo,
  Empty,
  End,
  Epsilon,
  Eq,
  EqDef,
  Equiangular,
  EquilibriumArrow,
  Equiv,
  Eta,
  EulerE,
  Exists,
  Exp,
  Expected,
  Expr,
  Factorial,
  FF,
  FilledCircle,
  FilledRhombus,
  FilledSquare,
  FlatSymbol,
  Floor,
  ForAll,
  Frac,
  FrakI,
  FrakR,
  Gamma,
  GammaU,
  GasMarker,
  Gcd,
  GCD,
  GDelta,
  GeoCong,
  GeoSim,
  Geq,
  Gg,
  Gimel,
  Grad,
  GreaterLess,
  Greek,
  Hadamard,
  Hat,
  HBar,
  Hexagon,
  Hom,
  HookLeftArrow,
  HookRightArrow,
  Iff,
  Im,
  ImagUnit,
  Img,
  Implies,
  In,
  Inf,
  InfSym,
  Integral,
  Intersect,
  Interval,
  Inverse,
  Iota,
  Kappa,
  Ker,
  Ket,
  Lambda,
  LambdaU,
  Lapl,
  Laplacian,
  Lcm,
  LCM,
  LDots,
  LeftArrow,
  LeftHarpoonDown,
  LeftHarpoonUp,
  LeftRightArrow,
  Leq,
  LessGreater,
  Lim,
  Liminf,
  Limsup,
  Ll,
  Ln,
  Log,
  LongLeftArrow,
  LongLeftRightArrow,
  LongMapsTo,
  LongRightArrow,
  MapsTo,
  Matrix,
  Max,
  MeasuredAngle,
  Min,
  MinusPlus,
  Mod,
  Models,
  Mu,
  Nabla,
  Nand,
  NaturalLog,
  NaturalSymbol,
  NearArrow,
  Neq,
  NN,
  Nor,
  Norm,
  Not,
  NotAsympEq,
  NotCong,
  NotDivides,
  NotEq,
  NotExists,
  NotIn,
  NotModels,
  NotParallel,
  NotSim,
  NotSubset,
  NotSupset,
  NotTurnstile,
  Nu,
  NullOp,
  NwArrow,
  Omega,
  OmegaU,
  Or,
  Ord,
  OTimes,
  Overbrace,
  Parallel,
  Paren,
  PartialDiff,
  PDeriv,
  Pentagon,
  Percent,
  Perm,
  Permille,
  Perpendicular,
  Phi,
  PhiU,
  PiSym,
  PiU,
  PlanckH,
  PlusMinus,
  Pow,
  PowerSet,
  PP,
  Prec,
  PrecEq,
  PrecipitateMarker,
  Prime,
  PrimeOf,
  Prob,
  Prod,
  ProperSubset,
  ProperSupset,
  Proportion,
  Propto,
  Psi,
  PsiU,
  QED,
  QQ,
  Rank,
  Ratio,
  Ray,
  Re,
  ReactionArrow,
  Res,
  Rho,
  Rhombus,
  RightAngle,
  RightAngleCorner,
  RightHarpoonDown,
  RightHarpoonUp,
  RightTriangle,
  RR,
  ScriptA,
  ScriptB,
  ScriptC,
  ScriptD,
  ScriptE,
  ScriptEll,
  ScriptF,
  ScriptG,
  ScriptH,
  ScriptI,
  ScriptJ,
  ScriptK,
  ScriptL,
  ScriptM,
  ScriptN,
  ScriptO,
  ScriptP,
  ScriptQ,
  ScriptR,
  ScriptS,
  ScriptT,
  ScriptU,
  ScriptV,
  ScriptW,
  ScriptX,
  ScriptY,
  ScriptZ,
  SeArrow,
  Sec,
  Segment,
  SetMinus,
  SetOf,
  Sgn,
  SharpSymbol,
  SigmaSym,
  SigmaU,
  Sim,
  Sin,
  SingleBond,
  Sinh,
  SmallInt,
  SpanOp,
  SphericalAngle,
  Sqrt,
  Square,
  Squared,
  Star,
  StdDev,
  Sub,
  SubOne,
  Subset,
  SubsetEq,
  SubTwo,
  SubZero,
  Succ,
  SuccEq,
  Sum,
  Sup,
  Supset,
  SupsetEq,
  SurfaceInt,
  SwArrow,
  Tan,
  Tanh,
  Tau,
  Therefore,
  Theta,
  ThetaU,
  Tilde,
  Times,
  Tombstone,
  Top,
  Trace,
  Transpose,
  Triangle,
  TripleBond,
  TripleInt,
  TriplePrime,
  Turnstile,
  TwoHeadLeft,
  TwoHeadRight,
  Underbrace,
  Union,
  UpArrow,
  UpDots,
  UpDownArrow,
  Upsilon,
  Varepsilon,
  Variance,
  Varphi,
  Varpi,
  Varrho,
  Varsigma,
  Vartheta,
  VDots,
  Vec,
  VolumeInt,
  Weierstrass,
  WreathProduct,
  Xi,
  XiU,
  Xor,
  Zeta,
  ZZ,
} from "@/components/mdx/math-primitives";
import { Equation, EqSystem } from "@/components/mdx/math-equation";
import {
  Solution,
  SolutionStep,
  SolutionAnswer,
  SolutionNote,
} from "@/components/mdx/math-solution";
import { ME, BME } from "@/components/mdx/math-easy";
import {
  DSArray,
  DSMatrix,
  DSLinkedList,
  DSDoublyLinkedList,
  DSCircularLinkedList,
  DSStack,
  DSQueue,
  DSDeque,
  DSPriorityQueue,
  DSBinaryTree,
  DSBST,
  DSMinHeap,
  DSMaxHeap,
  DSTrie,
  DSGraph,
  DSDigraph,
  DSWeightedGraph,
  DSDAG,
  DSHashMap,
  DSHashSet,
  DSNaryTree,
  DSSegmentTree,
  DSBFS,
  DSDFS,
  DSAgentFlow,
} from "@/components/mdx/ds";

const components = {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
  Badge,
  Blockquote,
  Callout,
  Steps,
  Step,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Tree,
  TreeItem,
  FileTree,
  Headings,
  Paragraph,
  Lead,
  Intro,
  Large,
  Small,
  Muted,
  Math,
  BlockMath,
  InlineMath,
  M,
  BM,
  Mermaid,
  MermaidBST,
  MermaidTree,
  MermaidBFS,
  MermaidDFS,
  CodeGroup,
  Alert,
  AlertTitle,
  AlertDescription,
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
  LinkCard,
  Kbd,
  Link,
  Spoiler,
  Annotation,
  Reveal,
  Preview,
  Demo,
  SymbolBrowser,
  Sandbox,
  GlossaryProvider,
  Term,
  Video,
  Image,
  ImageGlossary,
  DataTable,
  Highlight,
  DiffBlock,
  Terminal,
  TerminalLine,
  Changelog,
  ChangelogEntry,
  ChangelogItem,
  JsonLd,
  Definition,
  Invariant,
  ComplexityTable,
  HardwareSpec,
  DataTypeTable,
  SecurityNote,
  RegisterMap,
  PrivacyTable,
  CertificationBadge,
  // math-primitives (all 370+ exports)
  Abs,
  Aleph,
  Alpha,
  Amalg,
  And,
  Angle,
  AngleBracket,
  Angstrom,
  Approaches,
  Approx,
  Arc,
  ArcCos,
  ArcSin,
  ArcTan,
  Arg,
  Arrow,
  AsympEq,
  Aut,
  Bar,
  Because,
  Beta,
  Beth,
  BigAnd,
  BigIntersect,
  BigOr,
  BigUnion,
  Bot,
  Bowtie,
  Bra,
  Brace,
  BraKet,
  Bullet,
  Cardinality,
  Case,
  Cases,
  CC,
  CDots,
  Ceil,
  ChemEquilibrium,
  Chi,
  Choose,
  Circle,
  CircleArrow,
  CircleArrowLeft,
  CircledDiv,
  CircledMinus,
  CircledPlus,
  CircledStar,
  CircledTimes,
  Complex,
  Compose,
  CondProb,
  Cong,
  Conj,
  ContourIntegral,
  Contradiction,
  Convo,
  Corr,
  Corresponds,
  Cos,
  Cosh,
  Cot,
  Cov,
  Cross,
  Csc,
  Cubed,
  Dagger,
  Daleth,
  DDot,
  DDots,
  DefEq,
  DefinedAs,
  Deg,
  DegNum,
  DeltaU,
  Der,
  Deriv,
  Det,
  Diameter,
  Diamond,
  Differential,
  Digamma,
  Dim,
  DirectSum,
  Dist,
  Divides,
  Division,
  Dot,
  DotAccent,
  DoubleBond,
  DoubleBracket,
  DoubleDagger,
  DoubleDownArrow,
  DoubleHarpoon,
  DoubleInt,
  DoubleLeftArrow,
  DoubleLeftRightArrow,
  DoublePrime,
  DoubleRightArrow,
  DoubleUpArrow,
  DoubleUpDownArrow,
  DownArrow,
  Ellipse,
  EllTwo,
  Empty,
  End,
  Epsilon,
  Eq,
  EqDef,
  Equiangular,
  EquilibriumArrow,
  Equiv,
  Eta,
  EulerE,
  Exists,
  Exp,
  Expected,
  Expr,
  Factorial,
  FF,
  FilledCircle,
  FilledRhombus,
  FilledSquare,
  FlatSymbol,
  Floor,
  ForAll,
  Frac,
  FrakI,
  FrakR,
  Gamma,
  GammaU,
  GasMarker,
  Gcd,
  GCD,
  GDelta,
  GeoCong,
  GeoSim,
  Geq,
  Gg,
  Gimel,
  Grad,
  GreaterLess,
  Greek,
  Hadamard,
  Hat,
  HBar,
  Hexagon,
  Hom,
  HookLeftArrow,
  HookRightArrow,
  Iff,
  Im,
  ImagUnit,
  Img,
  Implies,
  In,
  Inf,
  InfSym,
  Integral,
  Intersect,
  Interval,
  Inverse,
  Iota,
  Kappa,
  Ker,
  Ket,
  Lambda,
  LambdaU,
  Lapl,
  Laplacian,
  Lcm,
  LCM,
  LDots,
  LeftArrow,
  LeftHarpoonDown,
  LeftHarpoonUp,
  LeftRightArrow,
  Leq,
  LessGreater,
  Lim,
  Liminf,
  Limsup,
  Ll,
  Ln,
  Log,
  LongLeftArrow,
  LongLeftRightArrow,
  LongMapsTo,
  LongRightArrow,
  MapsTo,
  Matrix,
  Max,
  MeasuredAngle,
  Min,
  MinusPlus,
  Mod,
  Models,
  Mu,
  Nabla,
  Nand,
  NaturalLog,
  NaturalSymbol,
  NearArrow,
  Neq,
  NN,
  Nor,
  Norm,
  Not,
  NotAsympEq,
  NotCong,
  NotDivides,
  NotEq,
  NotExists,
  NotIn,
  NotModels,
  NotParallel,
  NotSim,
  NotSubset,
  NotSupset,
  NotTurnstile,
  Nu,
  NullOp,
  NwArrow,
  Omega,
  OmegaU,
  Or,
  Ord,
  OTimes,
  Overbrace,
  Parallel,
  Paren,
  PartialDiff,
  PDeriv,
  Pentagon,
  Percent,
  Perm,
  Permille,
  Perpendicular,
  Phi,
  PhiU,
  PiSym,
  PiU,
  PlanckH,
  PlusMinus,
  Pow,
  PowerSet,
  PP,
  Prec,
  PrecEq,
  PrecipitateMarker,
  Prime,
  PrimeOf,
  Prob,
  Prod,
  ProperSubset,
  ProperSupset,
  Proportion,
  Propto,
  Psi,
  PsiU,
  QED,
  QQ,
  Rank,
  Ratio,
  Ray,
  Re,
  ReactionArrow,
  Res,
  Rho,
  Rhombus,
  RightAngle,
  RightAngleCorner,
  RightHarpoonDown,
  RightHarpoonUp,
  RightTriangle,
  RR,
  ScriptA,
  ScriptB,
  ScriptC,
  ScriptD,
  ScriptE,
  ScriptEll,
  ScriptF,
  ScriptG,
  ScriptH,
  ScriptI,
  ScriptJ,
  ScriptK,
  ScriptL,
  ScriptM,
  ScriptN,
  ScriptO,
  ScriptP,
  ScriptQ,
  ScriptR,
  ScriptS,
  ScriptT,
  ScriptU,
  ScriptV,
  ScriptW,
  ScriptX,
  ScriptY,
  ScriptZ,
  SeArrow,
  Sec,
  Segment,
  SetMinus,
  SetOf,
  Sgn,
  SharpSymbol,
  SigmaSym,
  SigmaU,
  Sim,
  Sin,
  SingleBond,
  Sinh,
  SmallInt,
  SpanOp,
  SphericalAngle,
  Sqrt,
  Square,
  Squared,
  Star,
  StdDev,
  Sub,
  SubOne,
  Subset,
  SubsetEq,
  SubTwo,
  SubZero,
  Succ,
  SuccEq,
  Sum,
  Sup,
  Supset,
  SupsetEq,
  SurfaceInt,
  SwArrow,
  Tan,
  Tanh,
  Tau,
  Therefore,
  Theta,
  ThetaU,
  Tilde,
  Times,
  Tombstone,
  Top,
  Trace,
  Transpose,
  Triangle,
  TripleBond,
  TripleInt,
  TriplePrime,
  Turnstile,
  TwoHeadLeft,
  TwoHeadRight,
  Underbrace,
  Union,
  UpArrow,
  UpDots,
  UpDownArrow,
  Upsilon,
  Varepsilon,
  Variance,
  Varphi,
  Varpi,
  Varrho,
  Varsigma,
  Vartheta,
  VDots,
  Vec,
  VolumeInt,
  Weierstrass,
  WreathProduct,
  Xi,
  XiU,
  Xor,
  Zeta,
  ZZ,
  // math-easy
  ME,
  BME,
  // math-equation
  Equation,
  EqSystem,
  Solution,
  SolutionStep,
  SolutionAnswer,
  SolutionNote,
  DSArray,
  DSMatrix,
  DSLinkedList,
  DSDoublyLinkedList,
  DSCircularLinkedList,
  DSStack,
  DSQueue,
  DSDeque,
  DSPriorityQueue,
  DSBinaryTree,
  DSBST,
  DSMinHeap,
  DSMaxHeap,
  DSTrie,
  DSGraph,
  DSDigraph,
  DSWeightedGraph,
  DSDAG,
  DSHashMap,
  DSHashSet,
  DSNaryTree,
  DSSegmentTree,
  DSBFS,
  DSDFS,
  DSAgentFlow,
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableRow,
  TableHead,
  TableCell,
  TableCaption,
  h1: H1,
  h2: H2,
  h3: H3,
  h4: H4,
  h5: H5,
  h6: H6,
  a: (props: React.AnchorHTMLAttributes<HTMLAnchorElement>) => (
    <Link {...props} />
  ),
  p: ({ className, ...props }: React.HTMLAttributes<HTMLParagraphElement>) => (
    <p className="text-base leading-7 [&:not(:first-child)]:mt-6" {...props} />
  ),
  ul: ({ className, ...props }: React.HTMLAttributes<HTMLUListElement>) => (
    <ul className="my-6 ml-6 list-disc space-y-2 [&>li]:mt-2" {...props} />
  ),
  ol: ({ className, ...props }: React.HTMLAttributes<HTMLOListElement>) => (
    <ol className="my-6 ml-6 list-decimal space-y-2 [&>li]:mt-2" {...props} />
  ),
  li: ({ className, ...props }: React.HTMLAttributes<HTMLElement>) => (
    <li className="mt-2" {...props} />
  ),
  blockquote: ({ className, ...props }: React.HTMLAttributes<HTMLElement>) => (
    <blockquote className="mt-6 border-l-2 pl-6 italic" {...props} />
  ),
  img: ({
    className,
    alt,
    ...props
  }: React.ImgHTMLAttributes<HTMLImageElement>) => (
    // eslint-disable-next-line @next/next/no-img-element
    <img className="rounded-md" alt={alt} {...props} />
  ),
  hr: ({ ...props }: React.HTMLAttributes<HTMLHRElement>) => (
    <hr className="my-4 md:my-8" {...props} />
  ),
  table: ({ className, ...props }: React.HTMLAttributes<HTMLTableElement>) => (
    <div className="my-6 w-full overflow-y-auto">
      <table className="w-full" {...props} />
    </div>
  ),
  tr: ({ className, ...props }: React.HTMLAttributes<HTMLTableRowElement>) => (
    <tr className="m-0 border-t p-0 even:bg-muted" {...props} />
  ),
  th: ({ className, ...props }: React.HTMLAttributes<HTMLTableCellElement>) => (
    <th
      className="border px-4 py-2 text-left font-bold [&[align=center]]:text-center [&[align=right]]:text-right"
      {...props}
    />
  ),
  td: ({ className, ...props }: React.HTMLAttributes<HTMLTableCellElement>) => (
    <td
      className="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right"
      {...props}
    />
  ),
  pre: (props: React.HTMLAttributes<HTMLPreElement>) => (
    <DocsCodeBlock {...props} />
  ),
  code: ({ className, ...props }: React.HTMLAttributes<HTMLElement>) => (
    <code
      className="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm"
      {...props}
    />
  ),
  div: ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => {
    if (className === "preview") {
      return <div className="my-6 rounded-lg border bg-card p-6" {...props} />;
    }
    return <div className={className} {...props} />;
  },
};

interface MdxProps {
  code: string;
}

export function Mdx({ code }: MdxProps) {
  const Component = useMDXComponent(code);

  return (
    <div className="mdx">
      <Component components={components} />
    </div>
  );
}
