// ─── Single source of truth for all component metadata ───────────────────────
// add.ts, remove.ts, update.ts and doctor.ts all derive their maps from here.

export interface ComponentEntry {
  /** Import path relative to componentsDir (e.g. "./alert") */
  importFile: string;
  /** Named exports to import (e.g. ["Alert", "AlertTitle"]) */
  imports: string[];
  /** HTML element → component overrides for mdx-components.tsx (e.g. { h1: "H1" }) */
  elementMappings: Record<string, string>;
  /** Files that make up this component (relative to componentsDir) */
  files: string[];
  /** npm packages required at runtime */
  deps: string[];
  /** Short description shown in list / add picker */
  description: string;
}

export const REGISTRY: Record<string, ComponentEntry> = {
  utils: {
    importFile: "./lib/utils",
    imports: ["cn"],
    elementMappings: {},
    files: ["lib/utils.ts"],
    deps: ["clsx", "tailwind-merge"],
    description: "Utility function cn() for merging Tailwind classes",
  },
  "ds-tree": {
    importFile: "./ds-tree",
    imports: [
      "DSTree",
      "DSBinaryTree",
      "DSBST",
      "DSAVLTree",
      "DSBalancedTree",
      "DSFullTree",
      "DSCompleteTree",
      "DSPerfectTree",
      "DSMinHeap",
      "DSMaxHeap",
      "DSNaryTree",
      "DSBSTPlayground",
    ],
    elementMappings: {},
    files: ["ds-tree.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Visual tree data structure diagrams (BST, AVL, heap, n-ary)",
  },
  ds: {
    importFile: "./ds",
    imports: [
      "DSArray",
      "DSMatrix",
      "DSLinkedList",
      "DSDoublyLinkedList",
      "DSCircularLinkedList",
      "DSStack",
      "DSQueue",
      "DSDeque",
      "DSPriorityQueue",
      "DSBinaryTree",
      "DSBST",
      "DSMinHeap",
      "DSMaxHeap",
      "DSTrie",
      "DSGraph",
      "DSDigraph",
      "DSWeightedGraph",
      "DSDAG",
      "DSHashMap",
      "DSHashSet",
      "DSNaryTree",
      "DSSegmentTree",
      "DSBFS",
      "DSDFS",
      "DSAgentFlow",
    ],
    elementMappings: {},
    files: ["ds.tsx"],
    deps: ["mermaid", "clsx", "tailwind-merge"],
    description:
      "Full data structures visualization suite (arrays, graphs, trees, etc.)",
  },
  annotation: {
    importFile: "./annotation",
    imports: ["Annotation"],
    elementMappings: {},
    files: ["annotation.tsx", "lib/primitives.ts"],
    deps: ["clsx", "tailwind-merge"],
    description: "Inline popover annotations for technical terms",
  },
  "certification-badge": {
    importFile: "./certification-badge",
    imports: ["CertificationBadge"],
    elementMappings: {},
    files: ["certification-badge.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Compliance and certification badges (ISO, SOC 2, GDPR, etc.)",
  },
  "data-type-table": {
    importFile: "./data-type-table",
    imports: ["DataTypeTable"],
    elementMappings: {},
    files: ["data-type-table.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description:
      "ML/hardware data type specifications table (INT8, FP16, BF16, etc.)",
  },
  "hardware-spec": {
    importFile: "./hardware-spec",
    imports: ["HardwareSpec"],
    elementMappings: {},
    files: ["hardware-spec.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Hardware specification comparison table",
  },
  "privacy-table": {
    importFile: "./privacy-table",
    imports: ["PrivacyTable"],
    elementMappings: {},
    files: ["privacy-table.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "GDPR/privacy policy data collection table",
  },
  "register-map": {
    importFile: "./register-map",
    imports: ["RegisterMap"],
    elementMappings: {},
    files: ["register-map.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Hardware/firmware register address map table",
  },
  "security-note": {
    importFile: "./security-note",
    imports: ["SecurityNote"],
    elementMappings: {},
    files: ["security-note.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description:
      "Security warnings with severity levels (critical, high, medium, low)",
  },
  "complexity-table": {
    importFile: "./complexity-table",
    imports: ["ComplexityTable"],
    elementMappings: {},
    files: ["complexity-table.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Algorithm time/space complexity table with Big-O notation",
  },
  definition: {
    importFile: "./definition",
    imports: ["Definition"],
    elementMappings: {},
    files: ["definition.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Term definition blocks with styled layout",
  },
  glossary: {
    importFile: "./glossary",
    imports: ["GlossaryProvider", "Term"],
    elementMappings: {},
    files: ["glossary.tsx", "lib/primitives.ts"],
    deps: ["clsx", "tailwind-merge"],
    description: "Inline glossary terms with hover definitions",
  },
  invariant: {
    importFile: "./invariant",
    imports: ["Invariant"],
    elementMappings: {},
    files: ["invariant.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description:
      "Algorithm invariant callout blocks with optional complexity badge",
  },
  preview: {
    importFile: "./preview",
    imports: ["Preview"],
    elementMappings: {},
    files: ["preview.tsx", "lib/primitives.ts"],
    deps: ["clsx", "tailwind-merge"],
    description: "Live component preview with tabbed source code view",
  },
  reveal: {
    importFile: "./reveal",
    imports: ["Reveal"],
    elementMappings: {},
    files: ["reveal.tsx", "lib/primitives.ts", "lib/motion.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Expandable reveal/show-more content section",
  },
  accordion: {
    importFile: "./accordion",
    imports: [
      "Accordion",
      "AccordionItem",
      "AccordionTrigger",
      "AccordionContent",
    ],
    elementMappings: {},
    files: ["accordion.tsx", "lib/primitives.ts", "lib/motion.tsx"],
    deps: [],
    description: "Collapsible accordion sections",
  },
  alert: {
    importFile: "./alert",
    imports: ["Alert", "AlertTitle", "AlertDescription"],
    elementMappings: {},
    files: ["alert.tsx"],
    deps: ["class-variance-authority", "clsx", "tailwind-merge"],
    description: "Alert banners with info/warning/destructive/success variants",
  },
  badge: {
    importFile: "./badge",
    imports: ["Badge"],
    elementMappings: {},
    files: ["badge.tsx"],
    deps: ["class-variance-authority", "clsx", "tailwind-merge"],
    description: "Status and label badges with multiple variants",
  },
  blockquote: {
    importFile: "./blockquote",
    imports: ["Blockquote"],
    elementMappings: { blockquote: "Blockquote" },
    files: ["blockquote.tsx"],
    deps: [],
    description: "Styled blockquote with optional citation",
  },
  callout: {
    importFile: "./callout",
    imports: ["Callout"],
    elementMappings: {},
    files: ["callout.tsx"],
    deps: ["class-variance-authority", "clsx", "tailwind-merge"],
    description: "Callout boxes for notes, warnings, tips, and errors",
  },
  card: {
    importFile: "./card",
    imports: [
      "Card",
      "CardHeader",
      "CardTitle",
      "CardDescription",
      "CardContent",
      "CardFooter",
      "LinkCard",
    ],
    elementMappings: {},
    files: ["card.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Content cards with header, body, and footer sections",
  },
  changelog: {
    importFile: "./changelog",
    imports: ["Changelog", "ChangelogEntry", "ChangelogItem"],
    elementMappings: {},
    files: ["changelog.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Versioned changelog with typed change entries",
  },
  "code-block": {
    importFile: "./code-block",
    imports: ["CodeBlock"],
    elementMappings: { pre: "CodeBlock" },
    files: ["code-block.tsx"],
    deps: [],
    description: "Syntax-highlighted code blocks with copy button",
  },
  "code-group": {
    importFile: "./code-group",
    imports: ["CodeGroup"],
    elementMappings: {},
    files: ["code-group.tsx"],
    deps: [],
    description: "Tabbed group of code blocks (e.g. npm/pnpm/yarn)",
  },
  "data-table": {
    importFile: "./data-table",
    imports: ["DataTable"],
    elementMappings: {},
    files: ["data-table.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Searchable and sortable data table",
  },
  "diff-block": {
    importFile: "./diff-block",
    imports: ["DiffBlock"],
    elementMappings: {},
    files: ["diff-block.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Git-style diff viewer with added/removed lines",
  },
  emphasis: {
    importFile: "./emphasis",
    imports: ["Strong", "Em"],
    elementMappings: { strong: "Strong", em: "Em" },
    files: ["emphasis.tsx"],
    deps: [],
    description: "Styled bold and italic text emphasis",
  },
  "file-tree": {
    importFile: "./file-tree",
    imports: ["FileTree"],
    elementMappings: {},
    files: ["file-tree.tsx"],
    deps: [],
    description: "Simple string-based file/folder tree display",
  },
  heading: {
    importFile: "./heading",
    imports: ["H1", "H2", "H3", "H4", "H5", "H6"],
    elementMappings: {
      h1: "H1",
      h2: "H2",
      h3: "H3",
      h4: "H4",
      h5: "H5",
      h6: "H6",
    },
    files: ["heading.tsx"],
    deps: ["class-variance-authority"],
    description: "Heading components H1–H6 with anchor links",
  },
  headings: {
    importFile: "./headings",
    imports: ["Headings"],
    elementMappings: {},
    files: ["headings.tsx"],
    deps: [],
    description: "Typography scale reference showing all heading levels",
  },
  highlight: {
    importFile: "./highlight",
    imports: ["Highlight"],
    elementMappings: {},
    files: ["highlight.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Inline text highlight marker",
  },
  "horizontal-rule": {
    importFile: "./horizontal-rule",
    imports: ["HorizontalRule"],
    elementMappings: { hr: "HorizontalRule" },
    files: ["horizontal-rule.tsx"],
    deps: [],
    description:
      "Styled horizontal divider lines (default, dashed, dotted, gradient)",
  },
  image: {
    importFile: "./image",
    imports: ["Image", "ImageGlossary"],
    elementMappings: { img: "Image" },
    files: ["image.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Images with optional captions and glossary overlay",
  },
  "inline-code": {
    importFile: "./inline-code",
    imports: ["Code"],
    elementMappings: { code: "Code" },
    files: ["inline-code.tsx"],
    deps: [],
    description: "Styled inline code snippets",
  },
  "json-ld": {
    importFile: "./json-ld",
    imports: ["JsonLd"],
    elementMappings: {},
    files: ["json-ld.tsx"],
    deps: [],
    description: "JSON-LD structured data script tag for SEO",
  },
  kbd: {
    importFile: "./kbd",
    imports: ["Kbd"],
    elementMappings: {},
    files: ["kbd.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Keyboard key badges (e.g. Ctrl+K)",
  },
  link: {
    importFile: "./link",
    imports: ["Link"],
    elementMappings: { a: "Link" },
    files: ["link.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Styled links with external indicator",
  },
  list: {
    importFile: "./list",
    imports: ["UnorderedList", "OrderedList", "ListItem"],
    elementMappings: { ul: "UnorderedList", ol: "OrderedList", li: "ListItem" },
    files: ["list.tsx"],
    deps: [],
    description: "Styled ordered and unordered lists",
  },
  math: {
    importFile: "./math",
    imports: ["Math", "BlockMath", "InlineMath"],
    elementMappings: {},
    files: ["math.tsx"],
    deps: ["katex", "clsx", "tailwind-merge"],
    description: "LaTeX math rendering with KaTeX (block and inline)",
  },
  mermaid: {
    importFile: "./mermaid",
    imports: [
      "Mermaid",
      "MermaidBST",
      "MermaidTree",
      "MermaidBFS",
      "MermaidDFS",
    ],
    elementMappings: {},
    files: ["mermaid.tsx"],
    deps: ["mermaid", "clsx", "tailwind-merge"],
    description: "Mermaid diagram renderer with BST/BFS/DFS variants",
  },
  paragraph: {
    importFile: "./paragraph",
    imports: ["Paragraph"],
    elementMappings: { p: "Paragraph" },
    files: ["paragraph.tsx"],
    deps: [],
    description: "Styled paragraph text component",
  },
  spoiler: {
    importFile: "./spoiler",
    imports: ["Spoiler"],
    elementMappings: {},
    files: ["spoiler.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Collapsible spoiler using native <details>/<summary>",
  },
  steps: {
    importFile: "./steps",
    imports: ["Steps", "Step"],
    elementMappings: {},
    files: ["steps.tsx"],
    deps: [],
    description: "Numbered step-by-step procedure guide",
  },
  table: {
    importFile: "./table",
    imports: [
      "Table",
      "TableHeader",
      "TableBody",
      "TableFooter",
      "TableRow",
      "TableHead",
      "TableCell",
      "TableCaption",
    ],
    elementMappings: {
      table: "Table",
      thead: "TableHeader",
      tbody: "TableBody",
      tfoot: "TableFooter",
      tr: "TableRow",
      th: "TableHead",
      td: "TableCell",
    },
    files: ["table.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Styled markdown table with full semantic elements",
  },
  tabs: {
    importFile: "./tabs",
    imports: ["Tabs", "TabsList", "TabsTrigger", "TabsContent"],
    elementMappings: {},
    files: ["tabs.tsx"],
    deps: [],
    description: "Interactive tabbed content panels",
  },
  terminal: {
    importFile: "./terminal",
    imports: ["Terminal", "TerminalLine"],
    elementMappings: {},
    files: ["terminal.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Terminal/shell output block with prompt styling",
  },
  tree: {
    importFile: "./tree",
    imports: ["Tree", "TreeItem"],
    elementMappings: {},
    files: ["tree.tsx"],
    deps: [],
    description: "Interactive file/folder tree with expand/collapse",
  },
  video: {
    importFile: "./video",
    imports: ["Video"],
    elementMappings: {},
    files: ["video.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description: "Responsive video embed with optional caption",
  },
  "math-primitives": {
    importFile: "./math-primitives",
    imports: [
      "Frac",
      "Pow",
      "Sub",
      "Sqrt",
      "Abs",
      "Deg",
      "Inf",
      "Greek",
      "Alpha",
      "Beta",
      "Gamma",
      "GDelta",
      "Epsilon",
      "Theta",
      "Lambda",
      "Mu",
      "PiSym",
      "Rho",
      "SigmaSym",
      "Tau",
      "Phi",
      "Omega",
      "GammaU",
      "DeltaU",
      "ThetaU",
      "LambdaU",
      "SigmaU",
      "PhiU",
      "OmegaU",
    ],
    elementMappings: {},
    files: ["math-primitives.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description:
      "Semantic math primitive atoms: Frac, Pow, Sub, Sqrt, Abs, Deg, Greek letters",
  },
  "math-equation": {
    importFile: "./math-equation",
    imports: [
      "Equation",
      "EqSystem",
      "Approx",
      "Neq",
      "Leq",
      "Geq",
      "Arrow",
      "Implies",
      "Iff",
    ],
    elementMappings: {},
    files: ["math-equation.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description:
      "Semantic equation display blocks: Equation, EqSystem, relation symbols",
  },
  "math-solution": {
    importFile: "./math-solution",
    imports: ["Solution", "SolutionStep", "SolutionAnswer", "SolutionNote"],
    elementMappings: {},
    files: ["math-solution.tsx"],
    deps: ["clsx", "tailwind-merge"],
    description:
      "Step-by-step mathematical solution blocks: Solution, SolutionStep, SolutionAnswer",
  },
  "math-easy": {
    importFile: "./math-easy",
    imports: ["ME", "BME"],
    elementMappings: {},
    files: ["math-easy.tsx"],
    deps: ["katex", "clsx", "tailwind-merge"],
    description:
      "Human-readable math DSL compiled to KaTeX — ME and BME (no backslashes needed)",
  },
};

// ─── Derived maps (consumed by add / remove / update / doctor) ────────────────

export const COMPONENT_MDX_MAP = Object.fromEntries(
  Object.entries(REGISTRY).map(([name, e]) => [
    name,
    {
      importFile: e.importFile,
      imports: e.imports,
      elementMappings: e.elementMappings,
    },
  ]),
);

export const COMPONENT_FILES = Object.fromEntries(
  Object.entries(REGISTRY).map(([name, e]) => [name, e.files]),
);

// Inverse of COMPONENT_FILES — used by update.ts to map filename → component name
export const FILE_TO_COMPONENT: Record<string, string> = Object.fromEntries(
  Object.entries(REGISTRY).flatMap(([name, e]) =>
    e.files.map((f) => [f, name]),
  ),
);

export const COMPONENT_DEPS = Object.fromEntries(
  Object.entries(REGISTRY).map(([name, e]) => [name, e.deps]),
);
