// ─── Symbol Map — single source of truth ─────────────────────────────────────
//
// Each entry maps a mathematical concept to its mdx-ui primitive component.
// Consumed by:
//   - MCP OUTPUT_STANDARD (built dynamically from this data)
//   - MCP tool: search_symbols
//   - MCP resource: registry://symbol-map
//   - CLI new command (content scaffolding hints)

export interface SymbolEntry {
  /** Human-readable concept name */
  name: string;
  /** Category for grouping */
  category: Category;
  /** Unicode / visual representations */
  symbols: string[];
  /** LaTeX equivalents (what someone familiar with LaTeX would type) */
  latex: string[];
  /** The primitive component name */
  component: string;
  /** Ready-to-paste MDX usage */
  usage: string;
  /** Short description */
  description: string;
}

export type Category =
  | "arithmetic"
  | "calculus"
  | "composition"
  | "trig"
  | "algebra"
  | "sets"
  | "logic"
  | "linear-algebra"
  | "probability"
  | "greek"
  | "relations"
  | "arrows"
  | "accents"
  | "brackets"
  | "geometry"
  | "physics"
  | "chemistry"
  | "script"
  | "operators"
  | "dots"
  | "definition"
  | "school"
  | "shorthands"
  | "misc"
  | "cs";

export const SYMBOL_MAP: SymbolEntry[] = [
  // ── Composition ─────────────────────────────────────────────────────────────
  {
    name: "expression / compose / group",
    category: "composition",
    symbols: [],
    latex: [],
    component: "Expr",
    usage: '<Expr>x <Pow exp="2">dx</Pow></Expr>',
    description:
      "Inline composition wrapper — groups text, symbols, and components into a single node",
  },
  // ── Arithmetic ──────────────────────────────────────────────────────────────
  {
    name: "plus / addition / unary plus",
    category: "arithmetic",
    symbols: ["+"],
    latex: ["+"],
    component: "Plus",
    usage: "<Plus />",
    description: "Plus sign +",
  },
  {
    name: "minus / subtraction / unary minus",
    category: "arithmetic",
    symbols: ["−", "-"],
    latex: ["-"],
    component: "Minus",
    usage: "<Minus />",
    description: "Minus sign − (U+2212, not a hyphen)",
  },
  {
    name: "multiply / multiplication",
    category: "arithmetic",
    symbols: ["×"],
    latex: ["\\times"],
    component: "Mul",
    usage: "<Mul />",
    description: "Multiplication sign × (inline)",
  },
  {
    name: "divide / division slash / inline division",
    category: "arithmetic",
    symbols: ["/"],
    latex: ["/"],
    component: "Div",
    usage: "<Div />",
    description: "Division slash / (inline a/b context)",
  },
  {
    name: "modulus / remainder / programming modulus",
    category: "arithmetic",
    symbols: ["%"],
    latex: ["\\%"],
    component: "Modulus",
    usage: "<Modulus />",
    description: "Modulus operator % (programming) — use Percent for math percent",
  },
  {
    name: "fraction",
    category: "arithmetic",
    symbols: ["a/b", "½", "¾"],
    latex: ["\\frac{a}{b}", "\\tfrac{a}{b}"],
    component: "Frac",
    usage: '<Frac num="a" den="b" />',
    description: "Vertical fraction with dividing line",
  },
  {
    name: "power / exponent / superscript",
    category: "arithmetic",
    symbols: ["x²", "xⁿ", "eˣ", "2³"],
    latex: ["x^{n}", "x^2", "e^x"],
    component: "Pow",
    usage: '<Pow exp="2">x</Pow>',
    description: "Raised exponent — base as children, exponent as exp prop",
  },
  {
    name: "subscript",
    category: "arithmetic",
    symbols: ["xₙ", "aᵢ", "x₀"],
    latex: ["x_{n}", "a_i", "x_0"],
    component: "Sub",
    usage: '<Sub sub="n">x</Sub>',
    description: "Lowered subscript — base as children, subscript as sub prop",
  },
  {
    name: "square root",
    category: "arithmetic",
    symbols: ["√x", "√(a+b)"],
    latex: ["\\sqrt{x}", "\\sqrt{a+b}"],
    component: "Sqrt",
    usage: "<Sqrt>x</Sqrt>",
    description: "Square root with overbar",
  },
  {
    name: "nth root / cube root",
    category: "arithmetic",
    symbols: ["ⁿ√x", "∛x", "∜x"],
    latex: ["\\sqrt[n]{x}", "\\sqrt[3]{x}"],
    component: "Sqrt",
    usage: '<Sqrt n="3">x</Sqrt>',
    description: "Nth root — index as n prop",
  },
  {
    name: "absolute value",
    category: "arithmetic",
    symbols: ["|x|", "|a − b|"],
    latex: ["\\left|x\\right|", "\\abs{x}"],
    component: "Abs",
    usage: "<Abs>x</Abs>",
    description: "Absolute value bars",
  },
  {
    name: "parentheses / grouping",
    category: "arithmetic",
    symbols: ["(a+b)", "(expr)"],
    latex: ["\\left(a+b\\right)"],
    component: "Paren",
    usage: "<Paren>a + b</Paren>",
    description: "Auto-sized parentheses",
  },
  {
    name: "infinity",
    category: "arithmetic",
    symbols: ["∞"],
    latex: ["\\infty"],
    component: "Inf",
    usage: "<Inf />",
    description: "Infinity symbol ∞",
  },
  {
    name: "degree symbol",
    category: "arithmetic",
    symbols: ["90°", "180°"],
    latex: ["90^\\circ"],
    component: "Deg",
    usage: "<Deg>90</Deg>",
    description: "Degree symbol as superscript",
  },
  {
    name: "division / obelus",
    category: "school",
    symbols: ["÷"],
    latex: ["\\div"],
    component: "Division",
    usage: "<Division />",
    description: "Division sign ÷ (elementary math)",
  },
  {
    name: "multiplication / times",
    category: "school",
    symbols: ["×"],
    latex: ["\\times"],
    component: "Times",
    usage: "<Times />",
    description: "Multiplication cross ×",
  },
  {
    name: "percent",
    category: "school",
    symbols: ["%"],
    latex: ["\\%"],
    component: "Percent",
    usage: "<Percent />",
    description: "Percent sign %",
  },
  {
    name: "per mille / per thousand",
    category: "school",
    symbols: ["‰"],
    latex: ["\\permille"],
    component: "Permille",
    usage: "<Permille />",
    description: "Per mille sign ‰",
  },
  {
    name: "proportion",
    category: "school",
    symbols: ["∷", "a:b = c:d"],
    latex: ["\\propto", "::"],
    component: "Proportion",
    usage: "<Proportion />",
    description: "Proportion symbol ∷ (a:b ∷ c:d)",
  },
  {
    name: "ratio",
    category: "school",
    symbols: ["∶"],
    latex: [":"],
    component: "Ratio",
    usage: "<Ratio />",
    description: "Ratio colon ∶",
  },
  {
    name: "plus or minus",
    category: "arithmetic",
    symbols: ["±"],
    latex: ["\\pm"],
    component: "PlusMinus",
    usage: "<PlusMinus />",
    description: "Plus-minus sign ±",
  },
  {
    name: "minus or plus",
    category: "arithmetic",
    symbols: ["∓"],
    latex: ["\\mp"],
    component: "MinusPlus",
    usage: "<MinusPlus />",
    description: "Minus-plus sign ∓",
  },

  // ── Calculus ─────────────────────────────────────────────────────────────────
  {
    name: "integral / indefinite integral",
    category: "calculus",
    symbols: ["∫", "∫f(x)dx"],
    latex: ["\\int f(x)\\,dx"],
    component: "Integral",
    usage: "<Integral>f(x) dx</Integral>",
    description: "Integral sign with integrand as children",
  },
  {
    name: "definite integral / bounded integral",
    category: "calculus",
    symbols: ["∫ₐᵇ", "∫₀¹"],
    latex: ["\\int_a^b f(x)\\,dx"],
    component: "Integral",
    usage: '<Integral from="a" to="b">f(x) dx</Integral>',
    description: "Integral with lower and upper bounds",
  },
  {
    name: "contour integral / line integral",
    category: "calculus",
    symbols: ["∮"],
    latex: ["\\oint"],
    component: "ContourIntegral",
    usage: "<ContourIntegral>f dz</ContourIntegral>",
    description: "Closed curve integral ∮",
  },
  {
    name: "double integral",
    category: "calculus",
    symbols: ["∬"],
    latex: ["\\iint"],
    component: "DoubleInt",
    usage: "<DoubleInt />",
    description: "Double integral ∬",
  },
  {
    name: "triple integral",
    category: "calculus",
    symbols: ["∭"],
    latex: ["\\iiint"],
    component: "TripleInt",
    usage: "<TripleInt />",
    description: "Triple integral ∭",
  },
  {
    name: "summation / sigma notation",
    category: "calculus",
    symbols: ["∑", "Σ"],
    latex: ["\\sum_{i=0}^{n}"],
    component: "Sum",
    usage: '<Sum from="i=0" to="n">aᵢ</Sum>',
    description: "Summation with index bounds",
  },
  {
    name: "product notation / pi notation",
    category: "calculus",
    symbols: ["∏", "Π"],
    latex: ["\\prod_{i=1}^{n}"],
    component: "Prod",
    usage: '<Prod from="i=1" to="n">aᵢ</Prod>',
    description: "Product with index bounds",
  },
  {
    name: "limit",
    category: "calculus",
    symbols: ["lim", "lim_{x→0}"],
    latex: ["\\lim_{x \\to 0}"],
    component: "Lim",
    usage: '<Lim sub="x → 0">f(x)</Lim>',
    description: "Limit with subscript condition",
  },
  {
    name: "derivative / first derivative",
    category: "calculus",
    symbols: ["dy/dx", "d/dx", "f′"],
    latex: ["\\frac{d}{dx}", "\\frac{dy}{dx}"],
    component: "Deriv",
    usage: '<Deriv of="y" by="x" />',
    description: "Leibniz derivative notation",
  },
  {
    name: "partial derivative",
    category: "calculus",
    symbols: ["∂f/∂x", "∂/∂x"],
    latex: ["\\frac{\\partial f}{\\partial x}"],
    component: "PDeriv",
    usage: '<PDeriv of="f" by="x" />',
    description: "Partial derivative ∂f/∂x",
  },
  {
    name: "nabla / gradient / del",
    category: "calculus",
    symbols: ["∇", "∇f", "grad f"],
    latex: ["\\nabla", "\\nabla f"],
    component: "Nabla",
    usage: "<Nabla />",
    description: "Nabla / del operator ∇",
  },
  {
    name: "Laplacian",
    category: "calculus",
    symbols: ["∇²", "Δ", "▲"],
    latex: ["\\nabla^2", "\\Delta", "\\laplacian"],
    component: "Laplacian",
    usage: "<Laplacian />",
    description: "Laplace operator ∇²",
  },
  {
    name: "differential / upright d",
    category: "calculus",
    symbols: ["dx", "dt", "dV"],
    latex: ["\\,dx", "\\mathrm{d}x"],
    component: "Differential",
    usage: "<Differential />x",
    description: "Upright roman d for differentials",
  },
  {
    name: "overbrace with label",
    category: "calculus",
    symbols: ["⏞"],
    latex: ["\\overbrace{x+y}^{n}"],
    component: "Overbrace",
    usage: '<Overbrace label="n terms">x + y + z</Overbrace>',
    description: "Curly brace above expression with annotation",
  },
  {
    name: "underbrace with label",
    category: "calculus",
    symbols: ["⏟"],
    latex: ["\\underbrace{x+y}_{n}"],
    component: "Underbrace",
    usage: '<Underbrace label="n terms">x + y + z</Underbrace>',
    description: "Curly brace below expression with annotation",
  },

  // ── Trigonometry ─────────────────────────────────────────────────────────────
  {
    name: "sine",
    category: "trig",
    symbols: ["sin", "sin θ"],
    latex: ["\\sin\\theta"],
    component: "Sin",
    usage: "<Sin /><Theta />",
    description: "Sine function",
  },
  {
    name: "cosine",
    category: "trig",
    symbols: ["cos", "cos θ"],
    latex: ["\\cos\\theta"],
    component: "Cos",
    usage: "<Cos /><Theta />",
    description: "Cosine function",
  },
  {
    name: "tangent",
    category: "trig",
    symbols: ["tan", "tan θ"],
    latex: ["\\tan\\theta"],
    component: "Tan",
    usage: "<Tan /><Theta />",
    description: "Tangent function",
  },
  {
    name: "arcsine / inverse sine",
    category: "trig",
    symbols: ["arcsin", "sin⁻¹"],
    latex: ["\\arcsin", "\\sin^{-1}"],
    component: "ArcSin",
    usage: "<ArcSin />",
    description: "Inverse sine function",
  },
  {
    name: "arccosine / inverse cosine",
    category: "trig",
    symbols: ["arccos", "cos⁻¹"],
    latex: ["\\arccos", "\\cos^{-1}"],
    component: "ArcCos",
    usage: "<ArcCos />",
    description: "Inverse cosine function",
  },
  {
    name: "arctangent / inverse tangent",
    category: "trig",
    symbols: ["arctan", "tan⁻¹"],
    latex: ["\\arctan", "\\tan^{-1}"],
    component: "ArcTan",
    usage: "<ArcTan />",
    description: "Inverse tangent function",
  },
  {
    name: "logarithm",
    category: "trig",
    symbols: ["log", "log₂", "log₁₀"],
    latex: ["\\log", "\\log_2"],
    component: "Log",
    usage: "<Log />",
    description: "Logarithm function",
  },
  {
    name: "natural logarithm",
    category: "trig",
    symbols: ["ln", "ln x"],
    latex: ["\\ln x"],
    component: "Ln",
    usage: "<Ln />",
    description: "Natural logarithm ln",
  },

  // ── Algebra & Combinatorics ───────────────────────────────────────────────────
  {
    name: "factorial",
    category: "algebra",
    symbols: ["n!", "5!"],
    latex: ["n!", "5!"],
    component: "Factorial",
    usage: "<Factorial>n</Factorial>",
    description: "Factorial n!",
  },
  {
    name: "binomial coefficient / n choose k",
    category: "algebra",
    symbols: ["C(n,k)", "ⁿCₖ", "(n k)"],
    latex: ["\\binom{n}{k}", "\\C{n}{k}"],
    component: "Choose",
    usage: '<Choose n="n" k="k" />',
    description: "Binomial coefficient C(n,k)",
  },
  {
    name: "floor function",
    category: "algebra",
    symbols: ["⌊x⌋"],
    latex: ["\\lfloor x \\rfloor", "\\floor{x}"],
    component: "Floor",
    usage: "<Floor>x</Floor>",
    description: "Floor function ⌊x⌋",
  },
  {
    name: "ceiling function",
    category: "algebra",
    symbols: ["⌈x⌉"],
    latex: ["\\lceil x \\rceil", "\\ceil{x}"],
    component: "Ceil",
    usage: "<Ceil>x</Ceil>",
    description: "Ceiling function ⌈x⌉",
  },
  {
    name: "modulo",
    category: "algebra",
    symbols: ["mod", "a mod n"],
    latex: ["a \\bmod n", "a \\mod n"],
    component: "Mod",
    usage: "<Mod>n</Mod>",
    description: "Modulo operation",
  },

  // ── Set Theory ──────────────────────────────────────────────────────────────
  {
    name: "element of / in",
    category: "sets",
    symbols: ["∈", "x ∈ A"],
    latex: ["\\in"],
    component: "In",
    usage: "<In />",
    description: "Element of ∈",
  },
  {
    name: "not element of",
    category: "sets",
    symbols: ["∉"],
    latex: ["\\notin"],
    component: "NotIn",
    usage: "<NotIn />",
    description: "Not element of ∉",
  },
  {
    name: "subset",
    category: "sets",
    symbols: ["⊂", "A ⊂ B"],
    latex: ["\\subset"],
    component: "Subset",
    usage: "<Subset />",
    description: "Subset ⊂",
  },
  {
    name: "proper subset / strict subset",
    category: "sets",
    symbols: ["⊊"],
    latex: ["\\subsetneq"],
    component: "ProperSubset",
    usage: "<ProperSubset />",
    description: "Proper subset ⊊ (not equal)",
  },
  {
    name: "union",
    category: "sets",
    symbols: ["∪", "A ∪ B"],
    latex: ["\\cup"],
    component: "Union",
    usage: "<Union />",
    description: "Set union ∪",
  },
  {
    name: "intersection",
    category: "sets",
    symbols: ["∩", "A ∩ B"],
    latex: ["\\cap"],
    component: "Intersect",
    usage: "<Intersect />",
    description: "Set intersection ∩",
  },
  {
    name: "big union / indexed union",
    category: "sets",
    symbols: ["⋃", "⋃ᵢ Aᵢ"],
    latex: ["\\bigcup_{i}"],
    component: "BigUnion",
    usage: '<BigUnion from="i=1" to="n">Aᵢ</BigUnion>',
    description: "N-ary union over index",
  },
  {
    name: "big intersection / indexed intersection",
    category: "sets",
    symbols: ["⋂", "⋂ᵢ Aᵢ"],
    latex: ["\\bigcap_{i}"],
    component: "BigIntersect",
    usage: '<BigIntersect from="i=1" to="n">Aᵢ</BigIntersect>',
    description: "N-ary intersection over index",
  },
  {
    name: "empty set",
    category: "sets",
    symbols: ["∅", "{}"],
    latex: ["\\emptyset", "\\varnothing"],
    component: "Empty",
    usage: "<Empty />",
    description: "Empty set ∅",
  },
  {
    name: "natural numbers",
    category: "sets",
    symbols: ["ℕ"],
    latex: ["\\mathbb{N}"],
    component: "NN",
    usage: "<NN />",
    description: "Set of natural numbers ℕ",
  },
  {
    name: "integers",
    category: "sets",
    symbols: ["ℤ"],
    latex: ["\\mathbb{Z}"],
    component: "ZZ",
    usage: "<ZZ />",
    description: "Set of integers ℤ",
  },
  {
    name: "real numbers",
    category: "sets",
    symbols: ["ℝ"],
    latex: ["\\mathbb{R}"],
    component: "RR",
    usage: "<RR />",
    description: "Set of real numbers ℝ",
  },
  {
    name: "complex numbers",
    category: "sets",
    symbols: ["ℂ"],
    latex: ["\\mathbb{C}"],
    component: "CC",
    usage: "<CC />",
    description: "Set of complex numbers ℂ",
  },

  // ── Logic ────────────────────────────────────────────────────────────────────
  {
    name: "logical and / conjunction",
    category: "logic",
    symbols: ["∧", "AND", "p ∧ q"],
    latex: ["\\land", "\\wedge"],
    component: "And",
    usage: "<And />",
    description: "Logical AND ∧",
  },
  {
    name: "logical or / disjunction",
    category: "logic",
    symbols: ["∨", "OR", "p ∨ q"],
    latex: ["\\lor", "\\vee"],
    component: "Or",
    usage: "<Or />",
    description: "Logical OR ∨",
  },
  {
    name: "logical not / negation",
    category: "logic",
    symbols: ["¬", "NOT", "~p"],
    latex: ["\\lnot", "\\neg"],
    component: "Not",
    usage: "<Not />",
    description: "Logical NOT ¬",
  },
  {
    name: "implies / conditional",
    category: "logic",
    symbols: ["⟹", "→", "p → q"],
    latex: ["\\Rightarrow", "\\implies"],
    component: "Implies",
    usage: "<Implies />",
    description: "Implication ⟹",
  },
  {
    name: "if and only if / biconditional",
    category: "logic",
    symbols: ["⟺", "↔", "p ↔ q"],
    latex: ["\\Leftrightarrow", "\\iff"],
    component: "Iff",
    usage: "<Iff />",
    description: "Biconditional ⟺",
  },
  {
    name: "for all / universal quantifier",
    category: "logic",
    symbols: ["∀", "∀x"],
    latex: ["\\forall"],
    component: "ForAll",
    usage: "<ForAll />",
    description: "Universal quantifier ∀",
  },
  {
    name: "there exists / existential quantifier",
    category: "logic",
    symbols: ["∃", "∃x"],
    latex: ["\\exists"],
    component: "Exists",
    usage: "<Exists />",
    description: "Existential quantifier ∃",
  },
  {
    name: "therefore",
    category: "logic",
    symbols: ["∴"],
    latex: ["\\therefore"],
    component: "Therefore",
    usage: "<Therefore />",
    description: "Therefore ∴",
  },
  {
    name: "because / since",
    category: "logic",
    symbols: ["∵"],
    latex: ["\\because"],
    component: "Because",
    usage: "<Because />",
    description: "Because ∵",
  },
  {
    name: "end of proof / QED",
    category: "logic",
    symbols: ["∎", "□", "QED"],
    latex: ["\\qed", "\\blacksquare"],
    component: "QED",
    usage: "<QED />",
    description: "End of proof ∎",
  },

  // ── Linear Algebra ────────────────────────────────────────────────────────────
  {
    name: "vector",
    category: "linear-algebra",
    symbols: ["v⃗", "→v", "bold v"],
    latex: ["\\vec{v}", "\\mathbf{v}"],
    component: "Vec",
    usage: "<Vec>v</Vec>",
    description: "Vector notation with arrow",
  },
  {
    name: "norm / magnitude",
    category: "linear-algebra",
    symbols: ["‖v‖", "|v|"],
    latex: ["\\|v\\|", "\\norm{v}"],
    component: "Norm",
    usage: "<Norm>v</Norm>",
    description: "Norm / magnitude ‖v‖",
  },
  {
    name: "determinant",
    category: "linear-algebra",
    symbols: ["det(A)", "|A|"],
    latex: ["\\det(A)", "\\det A"],
    component: "Det",
    usage: "<Det>A</Det>",
    description: "Determinant of a matrix",
  },
  {
    name: "transpose",
    category: "linear-algebra",
    symbols: ["Aᵀ", "A^T"],
    latex: ["A^T", "A^\\top"],
    component: "Transpose",
    usage: "<Transpose>A</Transpose>",
    description: "Matrix transpose Aᵀ",
  },
  {
    name: "matrix",
    category: "linear-algebra",
    symbols: ["[aᵢⱼ]", "2×2 matrix"],
    latex: ["\\begin{pmatrix}...\\end{pmatrix}"],
    component: "Matrix",
    usage: '<Matrix rows={[["a","b"],["c","d"]]} />',
    description: "Matrix with rows array",
  },
  {
    name: "dot product",
    category: "linear-algebra",
    symbols: ["·", "u·v"],
    latex: ["\\cdot", "u \\cdot v"],
    component: "Dot",
    usage: "<Dot />",
    description: "Dot product ·",
  },
  {
    name: "cross product",
    category: "linear-algebra",
    symbols: ["×", "u×v"],
    latex: ["\\times", "u \\times v"],
    component: "Cross",
    usage: "<Cross />",
    description: "Cross product ×",
  },

  // ── Probability & Statistics ──────────────────────────────────────────────────
  {
    name: "probability",
    category: "probability",
    symbols: ["P(A)", "Pr(A)"],
    latex: ["P(A)", "\\Pr(A)"],
    component: "Prob",
    usage: "<Prob>A</Prob>",
    description: "Probability P(A)",
  },
  {
    name: "conditional probability",
    category: "probability",
    symbols: ["P(A|B)"],
    latex: ["P(A|B)", "P(A \\mid B)"],
    component: "CondProb",
    usage: "<CondProb event={<>A</>} given={<>B</>} />",
    description: "Conditional probability P(A|B)",
  },
  {
    name: "expected value / expectation",
    category: "probability",
    symbols: ["E[X]", "𝔼[X]"],
    latex: ["\\mathbb{E}[X]", "\\E[X]"],
    component: "Expected",
    usage: "<Expected>X</Expected>",
    description: "Expected value E[X]",
  },
  {
    name: "variance",
    category: "probability",
    symbols: ["Var(X)", "σ²"],
    latex: ["\\text{Var}(X)", "\\sigma^2"],
    component: "Variance",
    usage: "<Variance>X</Variance>",
    description: "Variance Var(X)",
  },
  {
    name: "standard deviation",
    category: "probability",
    symbols: ["σ", "std(X)"],
    latex: ["\\sigma", "\\text{std}(X)"],
    component: "StdDev",
    usage: "<StdDev>X</StdDev>",
    description: "Standard deviation σ",
  },

  // ── Greek Letters ─────────────────────────────────────────────────────────────
  {
    name: "alpha",
    category: "greek",
    symbols: ["α"],
    latex: ["\\alpha"],
    component: "Alpha",
    usage: "<Alpha />",
    description: "Lowercase Greek alpha α",
  },
  {
    name: "beta",
    category: "greek",
    symbols: ["β"],
    latex: ["\\beta"],
    component: "Beta",
    usage: "<Beta />",
    description: "Lowercase Greek beta β",
  },
  {
    name: "gamma / Gamma",
    category: "greek",
    symbols: ["γ", "Γ"],
    latex: ["\\gamma", "\\Gamma"],
    component: "Gamma / GammaU",
    usage: "<Gamma /> or <GammaU />",
    description: "Greek gamma γ / Γ",
  },
  {
    name: "delta / Delta",
    category: "greek",
    symbols: ["δ", "Δ"],
    latex: ["\\delta", "\\Delta"],
    component: "GDelta / DeltaU",
    usage: "<GDelta /> or <DeltaU />",
    description: "Greek delta δ / Δ",
  },
  {
    name: "epsilon / varepsilon",
    category: "greek",
    symbols: ["ε", "ϵ"],
    latex: ["\\epsilon", "\\varepsilon"],
    component: "Epsilon / Varepsilon",
    usage: "<Epsilon /> or <Varepsilon />",
    description: "Greek epsilon ε",
  },
  {
    name: "theta / Theta",
    category: "greek",
    symbols: ["θ", "Θ"],
    latex: ["\\theta", "\\Theta"],
    component: "Theta / ThetaU",
    usage: "<Theta /> or <ThetaU />",
    description: "Greek theta θ / Θ",
  },
  {
    name: "lambda / Lambda",
    category: "greek",
    symbols: ["λ", "Λ"],
    latex: ["\\lambda", "\\Lambda"],
    component: "Lambda / LambdaU",
    usage: "<Lambda /> or <LambdaU />",
    description: "Greek lambda λ / Λ",
  },
  {
    name: "mu",
    category: "greek",
    symbols: ["μ"],
    latex: ["\\mu"],
    component: "Mu",
    usage: "<Mu />",
    description: "Greek mu μ (mean, micro)",
  },
  {
    name: "pi / Pi",
    category: "greek",
    symbols: ["π", "Π"],
    latex: ["\\pi", "\\Pi"],
    component: "PiSym / PiU",
    usage: "<PiSym /> or <PiU />",
    description: "Greek pi π / Π",
  },
  {
    name: "sigma / Sigma",
    category: "greek",
    symbols: ["σ", "Σ"],
    latex: ["\\sigma", "\\Sigma"],
    component: "SigmaSym / SigmaU",
    usage: "<SigmaSym /> or <SigmaU />",
    description: "Greek sigma σ / Σ",
  },
  {
    name: "phi / Phi / varphi",
    category: "greek",
    symbols: ["φ", "ϕ", "Φ"],
    latex: ["\\phi", "\\varphi", "\\Phi"],
    component: "Phi / PhiU / Varphi",
    usage: "<Phi /> or <PhiU /> or <Varphi />",
    description: "Greek phi φ / Φ",
  },
  {
    name: "omega / Omega",
    category: "greek",
    symbols: ["ω", "Ω"],
    latex: ["\\omega", "\\Omega"],
    component: "Omega / OmegaU",
    usage: "<Omega /> or <OmegaU />",
    description: "Greek omega ω / Ω",
  },

  // ── Relations ────────────────────────────────────────────────────────────────
  {
    name: "less than or equal",
    category: "relations",
    symbols: ["≤", "⩽"],
    latex: ["\\leq", "\\le"],
    component: "Leq",
    usage: "<Leq />",
    description: "Less than or equal ≤",
  },
  {
    name: "greater than or equal",
    category: "relations",
    symbols: ["≥", "⩾"],
    latex: ["\\geq", "\\ge"],
    component: "Geq",
    usage: "<Geq />",
    description: "Greater than or equal ≥",
  },
  {
    name: "not equal",
    category: "relations",
    symbols: ["≠"],
    latex: ["\\neq", "\\ne"],
    component: "Neq",
    usage: "<Neq />",
    description: "Not equal ≠",
  },
  {
    name: "approximately equal",
    category: "relations",
    symbols: ["≈"],
    latex: ["\\approx"],
    component: "Approx",
    usage: "<Approx />",
    description: "Approximately equal ≈",
  },
  {
    name: "equivalent / identical to",
    category: "relations",
    symbols: ["≡"],
    latex: ["\\equiv"],
    component: "Equiv",
    usage: "<Equiv />",
    description: "Equivalent / congruent mod n ≡",
  },
  {
    name: "proportional to",
    category: "relations",
    symbols: ["∝"],
    latex: ["\\propto"],
    component: "Propto",
    usage: "<Propto />",
    description: "Proportional to ∝",
  },

  // ── Definition & Equality ────────────────────────────────────────────────────
  {
    name: "defined as / assignment",
    category: "definition",
    symbols: [":=", "≜", "≝"],
    latex: [":=", "\\triangleq", "\\eqdef"],
    component: "DefEq / DefinedAs",
    usage: "<DefEq /> or <DefinedAs />",
    description: "Definition equals := or ≜",
  },
  {
    name: "approaches / limit definition",
    category: "definition",
    symbols: ["≐"],
    latex: ["\\doteq"],
    component: "Approaches",
    usage: "<Approaches />",
    description: "Approaches / equals at limit ≐",
  },
  {
    name: "corresponds to",
    category: "definition",
    symbols: ["≙"],
    latex: ["\\corresponds"],
    component: "Corresponds",
    usage: "<Corresponds />",
    description: "Corresponds to ≙",
  },

  // ── Arrows ───────────────────────────────────────────────────────────────────
  {
    name: "right arrow / tends to",
    category: "arrows",
    symbols: ["→"],
    latex: ["\\to", "\\rightarrow"],
    component: "Arrow",
    usage: "<Arrow />",
    description: "Right arrow →",
  },
  {
    name: "left arrow",
    category: "arrows",
    symbols: ["←"],
    latex: ["\\leftarrow", "\\gets"],
    component: "LeftArrow",
    usage: "<LeftArrow />",
    description: "Left arrow ←",
  },
  {
    name: "long right arrow / maps to",
    category: "arrows",
    symbols: ["⟶", "↦"],
    latex: ["\\longrightarrow", "\\mapsto"],
    component: "LongRightArrow / MapsTo",
    usage: "<LongRightArrow /> or <MapsTo />",
    description: "Long right arrow or maps to",
  },
  {
    name: "double right arrow / implies arrow",
    category: "arrows",
    symbols: ["⇒"],
    latex: ["\\Rightarrow"],
    component: "DoubleRightArrow",
    usage: "<DoubleRightArrow />",
    description: "Double right arrow ⇒",
  },
  {
    name: "equilibrium / reversible reaction",
    category: "arrows",
    symbols: ["⇌"],
    latex: ["\\rightleftharpoons"],
    component: "EquilibriumArrow",
    usage: "<EquilibriumArrow />",
    description: "Equilibrium / reversible arrow ⇌",
  },

  // ── Accents ──────────────────────────────────────────────────────────────────
  {
    name: "bar / mean / overline",
    category: "accents",
    symbols: ["x̄", "ā"],
    latex: ["\\bar{x}", "\\overline{x}"],
    component: "Bar",
    usage: "<Bar>x</Bar>",
    description: "Overline / mean x̄",
  },
  {
    name: "hat / estimate",
    category: "accents",
    symbols: ["x̂", "ŷ"],
    latex: ["\\hat{x}", "\\widehat{x}"],
    component: "Hat",
    usage: "<Hat>x</Hat>",
    description: "Hat accent x̂ (estimate or unit vector)",
  },
  {
    name: "tilde",
    category: "accents",
    symbols: ["x̃"],
    latex: ["\\tilde{x}", "\\widetilde{x}"],
    component: "Tilde",
    usage: "<Tilde>x</Tilde>",
    description: "Tilde accent x̃",
  },
  {
    name: "dot / first time derivative",
    category: "accents",
    symbols: ["ẋ", "ṙ"],
    latex: ["\\dot{x}"],
    component: "DotAccent",
    usage: "<DotAccent>x</DotAccent>",
    description: "Single dot (Newton notation ẋ)",
  },
  {
    name: "double dot / second time derivative",
    category: "accents",
    symbols: ["ẍ", "r̈"],
    latex: ["\\ddot{x}"],
    component: "DDot",
    usage: "<DDot>x</DDot>",
    description: "Double dot (Newton notation ẍ)",
  },
  {
    name: "prime / derivative shorthand",
    category: "accents",
    symbols: ["f′", "y′", "f″"],
    latex: ["f'", "f''", "f^{\\prime}"],
    component: "PrimeOf / Prime",
    usage: "<PrimeOf>f</PrimeOf> or f<Prime />",
    description: "Prime notation f′",
  },

  // ── Brackets ─────────────────────────────────────────────────────────────────
  {
    name: "curly brace grouping",
    category: "brackets",
    symbols: ["{x}", "{a+b}"],
    latex: ["\\left\\{ x \\right\\}", "\\{a+b\\}"],
    component: "Brace",
    usage: "<Brace>x + y</Brace>",
    description: "Curly brace grouping — scales to match content height",
  },
  {
    name: "angle brackets / inner product",
    category: "brackets",
    symbols: ["⟨u,v⟩", "⟨x⟩"],
    latex: ["\\langle u,v \\rangle", "\\inner{u}{v}"],
    component: "AngleBracket",
    usage: "<AngleBracket>u, v</AngleBracket>",
    description: "Angle brackets ⟨ ⟩",
  },
  {
    name: "interval notation",
    category: "brackets",
    symbols: ["[a,b]", "(a,b)", "[a,b)", "(a,b]"],
    latex: ["[a,b]", "(a,b)"],
    component: "Interval",
    usage: '<Interval a="0" b="1" leftOpen rightOpen />',
    description: "Interval [a,b] with open/closed ends",
  },
  {
    name: "double bracket / Iverson bracket",
    category: "brackets",
    symbols: ["⟦P⟧"],
    latex: ["\\llbracket P \\rrbracket"],
    component: "DoubleBracket",
    usage: "<DoubleBracket>P</DoubleBracket>",
    description: "Iverson bracket ⟦P⟧ = 1 if P true",
  },
  {
    name: "Dirac bra-ket",
    category: "physics",
    symbols: ["⟨ψ|φ⟩", "⟨ψ|", "|φ⟩"],
    latex: ["\\langle\\psi|\\phi\\rangle"],
    component: "BraKet / Bra / Ket",
    usage: "<BraKet bra={<Psi />} ket={<Phi />} />",
    description: "Dirac notation ⟨ψ|φ⟩",
  },

  // ── Geometry ─────────────────────────────────────────────────────────────────
  {
    name: "angle",
    category: "geometry",
    symbols: ["∠ABC", "∠A"],
    latex: ["\\angle ABC"],
    component: "Angle",
    usage: "<Angle>ABC</Angle>",
    description: "Angle symbol ∠ABC",
  },
  {
    name: "measured angle",
    category: "geometry",
    symbols: ["∡ABC"],
    latex: ["\\measuredangle ABC"],
    component: "MeasuredAngle",
    usage: "<MeasuredAngle />",
    description: "Measured angle ∡ (arc with rays)",
  },
  {
    name: "triangle",
    category: "geometry",
    symbols: ["△ABC"],
    latex: ["\\triangle ABC"],
    component: "Triangle",
    usage: "<Triangle>ABC</Triangle>",
    description: "Triangle △ABC",
  },
  {
    name: "parallel",
    category: "geometry",
    symbols: ["∥", "AB ∥ CD"],
    latex: ["\\parallel"],
    component: "Parallel",
    usage: "<Parallel />",
    description: "Parallel lines ∥",
  },
  {
    name: "perpendicular",
    category: "geometry",
    symbols: ["⊥", "AB ⊥ CD"],
    latex: ["\\perp"],
    component: "Perpendicular",
    usage: "<Perpendicular />",
    description: "Perpendicular ⊥",
  },
  {
    name: "line segment",
    category: "geometry",
    symbols: ["AB̄"],
    latex: ["\\overline{AB}"],
    component: "Segment",
    usage: "<Segment>AB</Segment>",
    description: "Line segment with overbar AB̄",
  },
  {
    name: "diameter",
    category: "geometry",
    symbols: ["⌀", "⌀50mm"],
    latex: ["\\diameter"],
    component: "Diameter",
    usage: "<Diameter />",
    description: "Diameter symbol ⌀",
  },
  {
    name: "congruent",
    category: "geometry",
    symbols: ["≅", "△ABC ≅ △DEF"],
    latex: ["\\cong"],
    component: "GeoCong",
    usage: "<GeoCong />",
    description: "Congruent ≅",
  },
  {
    name: "similar",
    category: "geometry",
    symbols: ["∼", "△ABC ∼ △DEF"],
    latex: ["\\sim"],
    component: "GeoSim",
    usage: "<GeoSim />",
    description: "Similar ∼",
  },

  // ── Physics ──────────────────────────────────────────────────────────────────
  {
    name: "h-bar / reduced Planck constant",
    category: "physics",
    symbols: ["ℏ"],
    latex: ["\\hbar"],
    component: "HBar",
    usage: "<HBar />",
    description: "Reduced Planck constant ℏ",
  },
  {
    name: "Angstrom",
    category: "physics",
    symbols: ["Å"],
    latex: ["\\text{Å}", "\\angstrom"],
    component: "Angstrom",
    usage: "<Angstrom />",
    description: "Ångström unit Å",
  },
  {
    name: "convolution",
    category: "operators",
    symbols: ["∗", "f∗g"],
    latex: ["f * g", "f \\ast g"],
    component: "Convo",
    usage: "<Convo />",
    description: "Convolution operator ∗",
  },
  {
    name: "direct sum",
    category: "operators",
    symbols: ["⊕"],
    latex: ["\\oplus"],
    component: "DirectSum",
    usage: "<DirectSum />",
    description: "Direct sum ⊕",
  },

  // ── Script Letters ────────────────────────────────────────────────────────────
  {
    name: "Laplace transform",
    category: "script",
    symbols: ["ℒ{f}"],
    latex: ["\\mathcal{L}"],
    component: "ScriptL",
    usage: "<ScriptL />",
    description: "Script L — Laplace transform ℒ",
  },
  {
    name: "Fourier transform",
    category: "script",
    symbols: ["ℱ{f}"],
    latex: ["\\mathcal{F}"],
    component: "ScriptF",
    usage: "<ScriptF />",
    description: "Script F — Fourier transform ℱ",
  },
  {
    name: "Big-O notation",
    category: "script",
    symbols: ["𝒪(n)", "O(n log n)"],
    latex: ["\\mathcal{O}(n)"],
    component: "ScriptO",
    usage: "<ScriptO />(n)",
    description: "Script O — complexity notation 𝒪",
  },
  {
    name: "Hilbert space",
    category: "script",
    symbols: ["ℋ"],
    latex: ["\\mathcal{H}"],
    component: "ScriptH",
    usage: "<ScriptH />",
    description: "Script H — Hilbert space ℋ",
  },
  {
    name: "script ell / ell-p spaces",
    category: "script",
    symbols: ["ℓ", "ℓ²", "ℓᵖ"],
    latex: ["\\ell"],
    component: "ScriptEll",
    usage: "<ScriptEll />",
    description: "Script ell ℓ (length, sequence spaces)",
  },

  // ── Chemistry ────────────────────────────────────────────────────────────────
  {
    name: "chemical equilibrium arrow",
    category: "chemistry",
    symbols: ["⇌"],
    latex: ["\\rightleftharpoons"],
    component: "ChemEquilibrium",
    usage: "<ChemEquilibrium />",
    description: "Chemical equilibrium ⇌",
  },
  {
    name: "reaction arrow",
    category: "chemistry",
    symbols: ["⟶"],
    latex: ["\\longrightarrow"],
    component: "ReactionArrow",
    usage: "<ReactionArrow />",
    description: "Forward reaction arrow ⟶",
  },
  {
    name: "gas product marker",
    category: "chemistry",
    symbols: ["↑"],
    latex: ["\\uparrow"],
    component: "GasMarker",
    usage: "<GasMarker />",
    description: "Gas evolves ↑",
  },
  {
    name: "precipitate marker",
    category: "chemistry",
    symbols: ["↓"],
    latex: ["\\downarrow"],
    component: "PrecipitateMarker",
    usage: "<PrecipitateMarker />",
    description: "Precipitate forms ↓",
  },
  {
    name: "single bond",
    category: "chemistry",
    symbols: ["—", "C—H"],
    latex: ["-", "\\text{—}"],
    component: "SingleBond",
    usage: "C<SingleBond />H",
    description: "Single covalent bond —",
  },
  {
    name: "double bond",
    category: "chemistry",
    symbols: ["═", "C═O"],
    latex: ["=", "\\text{═}"],
    component: "DoubleBond",
    usage: "C<DoubleBond />O",
    description: "Double covalent bond ═",
  },
  {
    name: "triple bond",
    category: "chemistry",
    symbols: ["≡", "N≡N"],
    latex: ["\\equiv", "\\text{≡}"],
    component: "TripleBond",
    usage: "N<TripleBond />N",
    description: "Triple covalent bond ≡",
  },

  // ── Dots ─────────────────────────────────────────────────────────────────────
  {
    name: "horizontal dots / centered dots",
    category: "dots",
    symbols: ["⋯", "1 + 2 + ⋯ + n"],
    latex: ["\\cdots"],
    component: "CDots",
    usage: "<CDots /> or <CDots count={5} />",
    description: "Centered horizontal dots — count prop controls number of dots (default 3)",
  },
  {
    name: "vertical dots",
    category: "dots",
    symbols: ["⋮"],
    latex: ["\\vdots"],
    component: "VDots",
    usage: "<VDots />",
    description: "Vertical dots ⋮ (in matrices)",
  },
  {
    name: "diagonal dots",
    category: "dots",
    symbols: ["⋱"],
    latex: ["\\ddots"],
    component: "DDots",
    usage: "<DDots />",
    description: "Diagonal dots ⋱ (in matrices)",
  },
  {
    name: "baseline ellipsis",
    category: "dots",
    symbols: ["…", "1, 2, …, n"],
    latex: ["\\ldots"],
    component: "LDots",
    usage: "<LDots />",
    description: "Baseline ellipsis …",
  },

  // ── CS / Asymptotic Notation ─────────────────────────────────────────────────
  {
    name: "Big-O / worst-case complexity",
    category: "cs",
    symbols: ["O", "O(n)", "O(log n)"],
    latex: ["O(n)", "\\mathcal{O}(n)"],
    component: "BigO",
    usage: "<BigO />(n)",
    description: "Big-O upper bound — worst-case complexity",
  },
  {
    name: "Big-Theta / tight complexity bound",
    category: "cs",
    symbols: ["Θ", "Θ(n)"],
    latex: ["\\Theta(n)"],
    component: "BigTheta",
    usage: "<BigTheta />(n)",
    description: "Big-Theta tight bound — exact asymptotic complexity",
  },
  {
    name: "Big-Omega / best-case complexity",
    category: "cs",
    symbols: ["Ω", "Ω(n)"],
    latex: ["\\Omega(n)"],
    component: "BigOmega",
    usage: "<BigOmega />(n)",
    description: "Big-Omega lower bound — best-case complexity",
  },
  {
    name: "little-o / strict upper bound",
    category: "cs",
    symbols: ["𝑜", "o(n)"],
    latex: ["o(n)"],
    component: "LittleO",
    usage: "<LittleO />(n)",
    description: "little-o strict upper bound — f grows strictly slower than g",
  },
  {
    name: "little-omega / strict lower bound",
    category: "cs",
    symbols: ["ω", "ω(n)"],
    latex: ["\\omega(n)"],
    component: "LittleOmega",
    usage: "<LittleOmega />(n)",
    description:
      "little-omega strict lower bound — f grows strictly faster than g",
  },

  // ── Misc ─────────────────────────────────────────────────────────────────────
  {
    name: "aleph / cardinality of infinite sets",
    category: "misc",
    symbols: ["ℵ", "ℵ₀", "ℵ₁"],
    latex: ["\\aleph_0", "\\aleph_1"],
    component: "Aleph",
    usage: "<Aleph />",
    description: "Aleph ℵ (infinite cardinal)",
  },
];

// ─── Lookup helpers ─────────────────────────────────────────────────────────

/** Search the symbol map by name, LaTeX, symbol, or component name. */
export function searchSymbols(query: string): SymbolEntry[] {
  const q = query.toLowerCase().trim();
  return SYMBOL_MAP.filter((e) => {
    return (
      e.name.toLowerCase().includes(q) ||
      e.component.toLowerCase().includes(q) ||
      e.latex.some((l) => l.toLowerCase().includes(q)) ||
      e.symbols.some((s) => s.toLowerCase().includes(q)) ||
      e.description.toLowerCase().includes(q) ||
      e.category.toLowerCase().includes(q)
    );
  });
}

/** Get all entries for a category. */
export function symbolsByCategory(category: Category): SymbolEntry[] {
  return SYMBOL_MAP.filter((e) => e.category === category);
}

/** Get unique categories. */
export const CATEGORIES_LIST = [
  ...new Set(SYMBOL_MAP.map((e) => e.category)),
] as Category[];

/** Format a single entry as readable text for the MCP output standard. */
export function formatEntry(e: SymbolEntry): string {
  const sym = e.symbols.join(" / ");
  const latex = e.latex.slice(0, 2).join(" or ");
  return `${sym.padEnd(16)} → ${e.usage.padEnd(48)} (was: ${latex})`;
}

/** Build the math section of the OUTPUT_STANDARD dynamically from the map. */
export function buildMathStandard(): string {
  const lines: string[] = [
    "MATH — use primitive components only, never $ signs or LaTeX strings.",
    "SYMBOL MAP — for every mathematical symbol, use the component shown:",
    "",
  ];

  for (const cat of CATEGORIES_LIST) {
    const entries = symbolsByCategory(cat);
    if (entries.length === 0) continue;
    lines.push(
      `── ${cat.toUpperCase().replace(/-/g, " ")} ${"─".repeat(Math.max(0, 60 - cat.length))}`,
    );
    for (const e of entries) {
      lines.push(`  ${formatEntry(e)}`);
    }
    lines.push("");
  }

  lines.push(
    "COMPOSING NESTED EXPRESSIONS — wrap complex sub-expressions in {<span>...</span>}:",
    '  <Frac num={<span><Pow exp="2">x</Pow> + 1</span>} den="2a" />',
    '  <Integral from="0" to={<Inf />}><Pow exp={<span>−<Pow exp="2">x</Pow></span>}>e</Pow> dx</Integral>',
    "",
    "PIECEWISE FUNCTIONS:",
    "  <Cases>",
    '    <Case expr="x" when="x ≥ 0" />',
    '    <Case expr={<span>−x</span>} when="x < 0" />',
    "  </Cases>",
    "",
    "SOLUTION BLOCKS:",
    '  <Solution title="Solve: 2x + 4 = 10">',
    '    <SolutionStep reason="Subtract 4">2x = 6</SolutionStep>',
    '    <SolutionStep reason="Divide by 2" highlight>x = 3</SolutionStep>',
    "    <SolutionAnswer>x = 3</SolutionAnswer>",
    "  </Solution>",
    "",
    "STRICT RULES",
    "- NEVER use $...$ or $$...$$",
    "- NEVER use <InlineMath>, <BlockMath>, <Math>, <ME>, <BME>",
    "- NEVER use raw HTML tags",
    "- NEVER invent component names not in the symbol map above",
    "- NEVER use # (h1) headings — start with ##",
    "- String props: plain text. Nested primitives: {<span>...</span>}",
  );

  return lines.join("\n");
}
