name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.6

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build registry
        run: npm run build:registry

      - name: Build CLI
        run: pnpm run build --filter=@ravikumarsurya/mdx-ui

      - name: Publish to npm
        run: pnpm publish --filter=@ravikumarsurya/mdx-ui --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
